import{a as y,S as L,i as w}from"./assets/vendor-b42c18af.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&r(i)}).observe(document,{childList:!0,subtree:!0});function n(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(t){if(t.ep)return;t.ep=!0;const s=n(t);fetch(t.href,s)}})();const b="42576318-0e1c04293cd098153cdda1833",v="https://pixabay.com/api/";async function M(o,e,n=15){try{return(await y.get(v,{params:{key:b,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:n}})).data}catch(r){throw console.error("Error fetching data:",r),r}}function S(o){return o.map(e=>`
        <div class="gallery-item">
            <a class="gallery-link" href="${e.largeImageURL}">
                <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}">
            </a>
            <div class="gallery-image-info">
                <p class="image-info-item"><span class="image-items-text">Likes: </span>${e.likes}</p>
                <p class="image-info-item"><span class="image-items-text">Views: </span>${e.views}</p>
                <p class="image-info-item"><span class="image-items-text">Comments: </span>${e.comments}</p>
                <p class="image-info-item"><span class="image-items-text">Downloads: </span>${e.downloads}</p>
            </div>
        </div>
    `).join("")}const u=new L(".gallery-link",{captionsData:"alt",captionDelay:250}),f=document.querySelector("#searchForm"),c=document.querySelector(".gallery"),m=document.querySelector(".loader"),l=document.getElementById("loadMoreBtn");let p="",a=1;const d=15;f.addEventListener("submit",E);l.addEventListener("click",x);function E(o){o.preventDefault(),c.innerHTML="",a=1,p=f.elements.searchQuery.value.trim(),h()}async function x(){a++,h()}function B(){m.style.display="block"}function g(){m.style.display="none"}function I(){l.style.display="block"}function O(){l.style.display="none"}async function h(){try{B();const o=await M(p,a,d),e=o.hits,n=o.totalHits||0;e.length===0?showNoImagesMessage():(P(e),a*d>=n?(O(),$()):(I(),R()),u.refresh())}catch(o){console.error("Error fetching data:",o),g()}}function P(o){const e=S(o);c.insertAdjacentHTML("beforeend",e),g(),u.refresh()}function $(){w.info({fontSize:"large",close:!1,position:"topRight",messageColor:"white",timeout:2e3,backgroundColor:"gray",message:"We're sorry, but you've reached the end of search results."})}function R(){window.scrollBy({top:c.getBoundingClientRect().height*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
