import{a as y,S as h,i as L}from"./assets/vendor-b42c18af.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&r(i)}).observe(document,{childList:!0,subtree:!0});function n(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(t){if(t.ep)return;t.ep=!0;const s=n(t);fetch(t.href,s)}})();const w="42576318-0e1c04293cd098153cdda1833",b="https://pixabay.com/api/";async function v(o,e,n=15){try{return(await y.get(b,{params:{key:w,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:n}})).data}catch(r){throw console.error("Error fetching data:",r),r}}function M(o){return o.map(e=>`
        <div class="gallery-item">
            <a class="gallery-link" href="${e.largeImageURL}">
                <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}">
            </a>
            <div class="gallery-image-info">
                <p class="image-info-item"><span class="image-items-text">Likes: </span>${e.likes}</p>
                <p class="image-info-item"><span class="image-items-text">Views: </span>${e.views}</p>
                <p class="image-info-item"><span class="image-items-text">Comments: </span>${e.comments}</p>
                <p class="image-info-item"><span class="image-items-text">Downloads: </span>${e.downloads}</p>
            </div>
        </div>
    `).join("")}const S=new h(".gallery-link",{captionsData:"alt",captionDelay:250}),u=document.querySelector("#searchForm"),c=document.querySelector(".gallery"),f=document.querySelector(".loader"),l=document.getElementById("loadMoreBtn");let m="",a=1;const d=15;u.addEventListener("submit",E);l.addEventListener("click",x);function E(o){o.preventDefault(),c.innerHTML="",a=1,m=u.elements.searchQuery.value.trim(),g()}async function x(){a++,g()}function B(o){const e=M(o);c.insertAdjacentHTML("beforeend",e),p()}function I(){f.style.display="block"}function p(){f.style.display="none"}function O(){l.style.display="block"}function P(){l.style.display="none"}async function g(){try{I();const o=await v(m,a,d),e=o.hits,n=o.totalHits||0;e.length===0?showNoImagesMessage():(B(e),a*d>=n?(P(),$()):(O(),R(),S.refresh()))}catch(o){console.error("Error fetching data:",o),p()}}function $(){L.info({fontSize:"large",close:!1,position:"topRight",messageColor:"white",timeout:2e3,backgroundColor:"gray",message:"We're sorry, but you've reached the end of search results."})}function R(){window.scrollBy({top:c.getBoundingClientRect().height*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
